# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

target 'Health2.0' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SideMenuSwift'
  pod 'SideMenu'
  pod 'RealmSwift'
  pod 'BCryptSwift' 
  # Pods for Health2.0

end
