# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Health2.0' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SideMenuSwift'
  pod 'SideMenu'
  # Pods for Health2.0

end
